@startuml
Dashboard->NewsHandler:fillNewsFeed
NewsHandler->NewsTask:execute
OpenShiftCloud->keineahnungwiedieseiteheisst:getNews
return news
NewsTask->OpenShiftCloud:execute
return newJson
NewsHandler<--NewsTask: newsJson
Dashboard<--NewsHandler: news

@enduml